
server.error.whitelabel.enabled=false
spring.jpa.hibernate.ddl-auto=validate
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false
server.port=8080


service.client.url=https://site.trip-snap.org:3000
service.domain.root=trip-snap.org
service.domain.image=image.trip-snap.org

service.cloudfront.private-key=${CLOUDFRONT_PRIVATE_KEY_PATH}
service.cloudfront.key-pair-id=${CLOUDFRONT_KEY_PAIR_ID}